# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-13 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeployOperation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[(b'S', b'Static'), (b'D', b'Dynamic')], max_length=2)),
                ('operation_type', models.CharField(choices=[(b'N', b'New'), (b'NU', b'Not updated'), (b'U', b'Update'), (b'R', b'Remove')], max_length=2)),
                ('path', models.CharField(max_length=250)),
                ('hash', models.CharField(blank=True, max_length=128, null=True)),
                ('storage', models.BinaryField(max_length=250, null=True)),
                ('deploy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staticsites.Deploy')),
            ],
        ),
    ]
